import discord

ichika = discord.Embed(title='호시노 이치카(星乃一歌)', description='성별 : 여', color=0x33AAEE)
ichika.add_field(name='유닛', value='Leo/need', inline=False)
ichika.add_field(name='생일', value='8월 11일', inline=False)
ichika.add_field(name='키', value='161cm', inline=False)
ichika.add_field(name='학교', value='미야마스사카 여학원', inline=False)
ichika.add_field(name='반', value='1학년 C반', inline=False)
ichika.add_field(name='취미', value='미쿠의 노래 감상, 키우고 있는 선인장 바라보기', inline=False)
ichika.add_field(name='특기', value='사과 깎기', inline=False)
ichika.add_field(name='좋아하는 음식', value='야키소바 빵', inline=False)
ichika.add_field(name='싫어하는 음식', value='완두콩', inline=False)
ichika.add_field(name='약점', value='절규계 놀이기구', inline=False)
ichika.add_field(name='자기소개', value='쿨해 보이지만 사실은 친구를 생각하는 상냥한 소녀. 사키, 호나미, 시호와는 소꿉친구이지만, 어떤 사정으로 호나미와 시호와는 관계가 삐걱거리고 있다. 미쿠의 노래를 감상하는 것을 좋아한다. Leo/need에서는 기타와 보컬을 담당한다.', inline=False)
ichika.set_thumbnail(url="https://cdn.discordapp.com/attachments/858612609116012549/874186025327550494/63dd61b0407df850d61fe5f50337b2adc8b819c3bd2ee916db5549220bf1061ea89187b7afaf11683b444a7420275a986ac0.png")
ichika.set_footer(text='Project SEKAI COLOURFUL STAGE! feat.HATSUNE MIKU')

saki = discord.Embed(title='텐마 사키(天馬咲希)', description='성별 : 여', color=0xFFDD44)
saki.add_field(name='유닛', value='Leo/need', inline=False)
saki.add_field(name='생일', value='5월 9일', inline=False)
saki.add_field(name='키', value='159cm', inline=False)
saki.add_field(name='학교', value='미야마스사카 여학원', inline=False)
saki.add_field(name='반', value='1학년 C반', inline=False)
saki.add_field(name='취미', value='패션・메이크업 영상 시청, 비즈 악세사리 만들기', inline=False)
saki.add_field(name='특기', value='헤어 어레인지, 공기 놀이', inline=False)
saki.add_field(name='좋아하는 음식', value='스낵 과자', inline=False)
saki.add_field(name='싫어하는 음식', value='죽', inline=False)
saki.add_field(name='약점', value='외톨이', inline=False)
saki.add_field(name='자기소개', value='언제나 밝고 미소가 끊이지 않는 무드 메이커. 선천적으로 병약한 탓에 중학교는 거의 다니지 못했지만, 간신히 건강해져서 고등학교부터 복학한다. 오랜만에 재회할 소꿉친구들과 즐거운 고교 생활을 기대하고 있었지만... Leo/need에서는 키보드 담당.', inline=False)
saki.set_thumbnail(url="https://cdn.discordapp.com/attachments/858612609116012549/874186042377383946/f3ffe3bb44ea2215be47ec9fb4e75857a00fe67527eee01cfd29d86b3496030d861392aa569b704339133fada18a52ce06db.png")
saki.set_footer(text='Project SEKAI COLOURFUL STAGE! feat.HATSUNE MIKU')

saki = discord.Embed(title='텐마 사키(天馬咲希)', description='성별 : 여', color=0xFFDD44)
saki.add_field(name='유닛', value='Leo/need', inline=False)
saki.add_field(name='생일', value='5월 9일', inline=False)
saki.add_field(name='키', value='159cm', inline=False)
saki.add_field(name='학교', value='미야마스사카 여학원', inline=False)
saki.add_field(name='반', value='1학년 C반', inline=False)
saki.add_field(name='취미', value='패션・메이크업 영상 시청, 비즈 악세사리 만들기', inline=False)
saki.add_field(name='특기', value='헤어 어레인지, 공기 놀이', inline=False)
saki.add_field(name='좋아하는 음식', value='스낵 과자', inline=False)
saki.add_field(name='싫어하는 음식', value='죽', inline=False)
saki.add_field(name='약점', value='외톨이', inline=False)
saki.add_field(name='자기소개', value='언제나 밝고 미소가 끊이지 않는 무드 메이커. 선천적으로 병약한 탓에 중학교는 거의 다니지 못했지만, 간신히 건강해져서 고등학교부터 복학한다. 오랜만에 재회할 소꿉친구들과 즐거운 고교 생활을 기대하고 있었지만... Leo/need에서는 키보드 담당.', inline=False)
saki.set_thumbnail(url="https://cdn.discordapp.com/attachments/858612609116012549/874186042377383946/f3ffe3bb44ea2215be47ec9fb4e75857a00fe67527eee01cfd29d86b3496030d861392aa569b704339133fada18a52ce06db.png")
saki.set_footer(text='Project SEKAI COLOURFUL STAGE! feat.HATSUNE MIKU')